; see http://haraka.github.io/core/Outbound
;
; disabled (default: false)
disabled=false

; Default: 100. Specifies the maximum concurrent connections to make. 
; Note that if using cluster (multiple CPUs) then this will be multiplied by the number of CPUs that you have.
concurrency_max=400

; Set this to 0 to completely disable the pooling code.
; This value determines how many concurrent connections can be made to a single IP address (destination) in the pool. Default: 10 connections.
pool_concurrency_max=400

; Timeout for connecting to remote servers. Default: 30s
connect_timeout=60

; Outbound mail uses "pooled" connections. An unused pool connection will send a QUIT after this time. Default: 50s
; Pooled connections means that a mail to a particular IP address will hold that connection open and use it the next time it is requested.
; This helps with large scale outbound mail. 
; If you don't send lots of mail it is advised to lower the pool_timeout value since it may upset receiving mail servers.
; Setting this value to 0 will effectively disable the use of pools. 
; You may wish to set this if you have a get_mx hook that picks outbound servers on a per-email basis (rather than per-domain).
pool_timeout=30

; uncomment to disable tls for outbound mail
; enable_tls=false

; maxTempFailures (default: 13)

; load_pid_queue
; flush_queue

; always_split: default: false
; always_split=true

; received_header (default: "Haraka outbound")
; received_header=Haraka outbound

; inet_prefer (default: default)
; inet_prefer=v4
